nginx:
  restart: always
  container_name: baseshop_nginx_test
  image: beatpop/nginxlaravel
  ports:
   - "28080:80"
#  volumes:
#   - /mnt/workspace/beatpop/config/nginx/nginx.conf:/etc/nginx/nginx.conf
  volumes_from:
   - php
  links:
   - php

php:
  restart: always
  container_name: baseshop_php_test
  image: beatpop/php-fpm:7.2.10-odebug
  volumes:
   - "/mnt/workspace/beatpop/baseshop:/var/www/html"
   - "/mnt/workspace/beatpop/baseshop/storage/data:/var/www/html/storage/data"
  links:
   - db:db

db:
  restart: always
  container_name: baseshop_db_test
  image: beatpop/mysql:latest
  ports:
     - "28081:3306"
  volumes:
     - "../beatpop/data/mysql:/var/lib/mysql5.7"
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 1

redis:
  restart: always
  container_name: baseshop_redis_test
  image: redis:latest
  ports:
     - "6379:6379"